{{- if hasKey $.Values "borgslave" }}
{{- $configmaps := 0 }} 
{{- range $name,$data := $.Values.borgslave.configmaps | default dict }}
    {{- $configmaps = add1 $configmaps}}
{{- end }}
{{- range $name,$data := $.Values.borgslave.configmaps | default dict }}
{{- if gt $configmaps 1 }}
---
{{- end }}
apiVersion: v1
data:
  {{- range $key,$value := $data }}
    {{- if kindIs "string" $value }}
      {{- if contains "{{Release.Name}}" $value }}
  {{ $key }}: {{  $value | replace "{{Release.Name}}" $.Release.Name | quote }}
      {{- else }}
  {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- else }}
  {{ $key }}: {{ $value | toString | quote }}
    {{- end }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-borgslave-configmap-{{ $name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
