{{- if hasKey $.Values "borgslave" }}
{{- $secrets := 0 }} 
{{- range $name,$data := $.Values.borgslave.secrets | default dict }}
    {{- $secrets = add1 $secrets}}
{{- end }}
{{- range $name,$data := $.Values.borgslave.secrets | default dict }}
{{- if gt $secrets 1 }}
---
{{- end }}
apiVersion: v1
data:
  {{- range $key,$value := $data }}
    {{- if kindIs "string" $value }}
      {{- if contains "%s" $value }}
  {{ $key }}: {{ printf $value $.Release.Name | b64enc | quote }}
      {{- else }}
  {{ $key }}: {{ $value | b64enc | quote }}
      {{- end }}
    {{- else }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
    {{- end }}
  {{- end }}
kind: Secret
metadata:
  name: {{ $.Release.Name }}-borgslave-secret-{{ $name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}

