{{- if and $.Values.geoserver ($.Values.geoserver.clustering | default false)  (gt ($.Values.geoserver.replicas | default 1 | int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-geocluster
spec:
  minAvailable: {{ sub $.Values.geoserver.replicas 1 }}
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-{{ $.Release.Namespace}}-{{ $.Release.Name }}-geocluster
{{- end }}
