{{- if $.Values.geoserver.clustering | default false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-geoclusteradmin-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $.Values.geoserver.adminDomain | default (printf "%sadmin.dbca.wa.gov.au" $.Release.Name) }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-geoclusteradmin
                port:
                  number: {{ $.Values.geoserver.port | default 8080 }}
            path: /
            pathType: Prefix
{{- range $i,$domain := $.Values.geoserver.otherDomains | default list }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-geocluster-{{ $domain | replace "." "-" }}-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-geoclusteradmin
                port:
                  number: {{ $.Values.geoserver.port | default 8080 }}
            path: /geoserver/web
            pathType: Prefix
          - backend:
              service:
                name: {{ $.Release.Name }}-geocluster
                port:
                  number: {{ $.Values.geoserver.port | default 8080 }}
            path: /
            pathType: Prefix
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-geocluster-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $.Values.geoserver.domain | default (printf "%s.dbca.wa.gov.au" $.Release.Name) }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-geoclusteradmin
                port:
                  number: {{ $.Values.geoserver.port | default 8080 }}
            path: /geoserver/web
            pathType: Prefix
          - backend:
              service:
                name: {{ $.Release.Name }}-geocluster
                port:
                  number: {{ $.Values.geoserver.port | default 8080 }}
            path: /
            pathType: Prefix
{{- range $i,$v := untilStep 1 ($.Values.geoserver.replicas | default 2 | int ) 1 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-geoclusterslave{{$v}}-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ printf ($.Values.geoserver.slaveDomain | default (printf "%sslave%%d.dbca.wa.gov.au" $.Release.Name)) $v }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-geoclusterslave{{ $v }}
                port:
                  number: {{ $.Values.geoserver.port | default 8080 }}
            path: /
            pathType: Prefix
{{- end }}
{{- end }}
