{{- if ($.Values.geoserver.clustering | default false) }}
{{- $startupProbe :=  $.Values.geoserver.startupProbe | default dict }}
{{- $livenessProbe :=  $.Values.geoserver.livenessProbe | default dict }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-geocluster
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-{{ $.Release.Namespace}}-{{ $.Release.Name }}-geocluster
  podManagementPolicy: OrderedReady
  replicas: {{ $.Values.geoserver.replicas | default 2 }}
  revisionHistoryLimit: 10
  serviceName: {{ $.Release.Name }}-geocluster
  template:
    metadata:
      creationTimestamp: null
      labels:
        #same as matchLabels
        workload.user.cattle.io/workloadselector: apps.statefulset-{{ $.Release.Namespace}}-{{ $.Release.Name }}-geocluster
    spec:
      initContainers:
        - name: {{ $.Release.Name }}-geocluster-init
          image: {{ $.Values.geoserver.image }}
          imagePullPolicy: Always
          command:
            - /geoserver/bin/init_geoserver
          env:
            {{- if not (hasKey $.Values.geoserver.envs "CLUSTER_DURABILITY") }}
            - name: CLUSTER_DURABILITY
              value: "false"
            {{- end }}
            {{- if not (hasKey $.Values.geoserver.envs "BROKER_URL") }}
            - name: BROKER_URL
              value: "tcp://{{ $.Release.Name }}-mq:61616"
            - name: CLUSTERING
              value: "true"
            - name: EMBEDDED_BROKER
              value: "disabled"
            {{- end }}
            {{- range $key,$value := $.Values.geoserver.envs }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- range $name,$data := $.Values.geoserver.secrets | default dict }}
            - secretRef:
                name: {{ $.Release.Name }}-geoserver-secret-{{ $name }}
                optional: false
            {{- end }}
            {{- range $name,$data := $.Values.geoserver.configmaps | default dict }}
            - configMapRef:
                name: {{ $.Release.Name }}-geoserver-configmap-{{ $name }}
                optional: false
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            {{- if hasKey $.Values.geoserver "groupid" }}
            runAsGroup: {{ $.Values.geoserver.groupid }}
            {{- end }}
            {{- if hasKey $.Values.geoserver "userid" }}
            runAsUser: {{ $.Values.geoserver.userid }}
            runAsNonRoot: true
            {{- else}}
            runAsNonRoot: false
            {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: config-files
              mountPath: "/geoserver/settings"
            - name: scripts
              mountPath: "/geoserver/bin"
            {{- range $type,$volumes := $.Values.geoserver.volumes}}
            {{- range $name,$config := $volumes}}
            {{- range $i,$mount := $config.mounts }}
            - mountPath: {{ $mount.mountPath | quote }}
              name: {{ $name }}
              {{- if hasKey $mount "subPath" }}
              subPath: {{ $mount.subPath | quote }}
              {{- end }}
            {{- end }}  
            {{- end }}
            {{- end }}
      containers:
        - name: {{ $.Release.Name }}-geocluster
          image: {{ $.Values.geoserver.image }}
          imagePullPolicy: Always
          command:
            - /geoserver/bin/start_geoserver
          stdin: true
          stdinOnce: false
          tty: true
          env:
            - name: GEOSERVER_UID
              value: {{ $.Values.geoserver.userid | default 1000 | quote }}
            - name: GEOSERVER_GID
              value: {{ $.Values.geoserver.groupid | default 1000 | quote  }}
            - name: USER
              value: {{ $.Values.geoserver.user | default "geoserver" }}
            - name: GROUP_NAME
              value: {{ $.Values.geoserver.group | default "geoserver" }}
            - name: GEOSERVER_CSRF_WHITELIST
              value: {{ $.Values.geoserver.adminDomain | default (cat $.Release.Name "admin.dbca.wa.gov.au") | quote }}
            - name: CLUSTERING
              value: "true"
            {{- if not (hasKey $.Values.geoserver.envs "CLUSTER_DURABILITY") }}
            - name: CLUSTER_DURABILITY
              value: "false"
            - name: EMBEDDED_BROKER
              value: "disabled"
            {{- end }}
            {{- if not (hasKey $.Values.geoserver.envs "BROKER_URL") }}
            - name: BROKER_URL
              value: "tcp://{{ $.Release.Name }}-mq-headless:61616"
            {{- end }}
            {{- range $key,$value := $.Values.geoserver.envs }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- range $name,$data := $.Values.geoserver.secrets | default dict }}
            - secretRef:
                name: {{ $.Release.Name }}-geoserver-secret-{{ $name }}
                optional: false
            {{- end }}
            {{- range $name,$data := $.Values.geoserver.configmaps | default dict }}
            - configMapRef:
                name: {{ $.Release.Name }}-geoserver-configmap-{{ $name }}
                optional: false
            {{- end }}
          startupProbe:
            failureThreshold: {{ $startupProbe.failureThreshold | default 30 }}
            successThreshold: {{ $startupProbe.successThreshold | default 1 }}
            initialDelaySeconds: {{ $startupProbe.initialDelaySeconds | default 0 }}
            timeoutSeconds: {{ $startupProbe.timeoutSeconds | default 1 }}
            periodSeconds: {{ $startupProbe.periodSeconds | default 1 }}
            exec:
              command:
                - /geoserver/bin/geoserver_startup
          livenessProbe:
            failureThreshold: {{ $livenessProbe.failureThreshold | default 2 }}
            successThreshold: {{ $livenessProbe.successThreshold | default 1 }}
            initialDelaySeconds: {{ $livenessProbe.initialDelaySeconds | default 1 }}
            timeoutSeconds: {{ $livenessProbe.timeoutSeconds | default 1 }}
            periodSeconds: {{ $livenessProbe.periodSeconds | default 2 }}
            exec:
              command:
                - /geoserver/bin/geoserver_liveness
          {{- if $.Values.geoserver.resources }}
          resources:
{{ $.Values.geoserver.resources | toYaml | indent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            {{- if hasKey $.Values.geoserver "groupid" }}
            runAsGroup: {{ $.Values.geoserver.groupid }}
            {{- end }}
            {{- if hasKey $.Values.geoserver "userid" }}
            runAsUser: {{ $.Values.geoserver.userid }}
            runAsNonRoot: true
            {{- else}}
            runAsNonRoot: false
            {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: config-files
              mountPath: "/geoserver/settings"
            - name: scripts
              mountPath: "/geoserver/bin"
            {{- range $type,$volumes := $.Values.geoserver.volumes }}
            {{- range $name,$config := $volumes}}
            {{- range $i,$mount := $config.mounts }}
            - mountPath: {{ $mount.mountPath | quote }}
              name: {{ $name }}
              {{- if hasKey $mount "subPath" }}
              subPath: {{ $mount.subPath | quote }}
              {{- end }}
            {{- end }}  
            {{- end }}
            {{- end }}
            {{- range $name,$config := $.Values.geoserver.volumeClaimTemplates }}
            {{- range $i,$mount := $config.mounts }}
            - mountPath: {{ $mount.mountPath }}
              name: {{ $.Release.Name }}-geocluster-{{ $name }}
              {{- if hasKey $mount "subPath" }}
              subPath: {{ $mount.subPath }}
              {{- end }}
            {{- end }}  
            {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- if hasKey $.Values.geoserver "groupid" }}
      securityContext:
        fsGroup: {{ $.Values.geoserver.groupid }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- if $.Values.geoserver.tolerations }}
      tolerations:
{{ $.Values.geoserver.tolerations | toYaml | indent 8 }}
      {{- end }}
      volumes:
      - name: config-files
        configMap:
          name: {{ $.Release.Name }}-geoserver-configmap-config-files
          optional: false
          defaultMode: 0777
      - name: scripts
        configMap:
          name: {{ $.Release.Name }}-geoserver-configmap-scripts
          optional: false
          defaultMode: 0555
      {{- range $name,$config := get ($.Values.geoserver.volumes | default dict) "pvcs" | default dict }}
      - name: {{ $name }}
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-geoserver-{{ $name }}
      {{- end }}
  volumeClaimTemplates:
    {{- range $name,$config := $.Values.geoserver.volumeClaimTemplates }}
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ $.Release.Name }}-geocluster-{{ $name }}
        namespace: {{ $.Release.Namespace }}
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ $config.storage}}
        storageClassName: {{ $config.storageClassName | default "managed-csi-retain" }}
        volumeMode: {{ $config.volumeMode | default "Filesystem" }}
          {{- end }}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
{{- end }}
