{{- if hasKey $.Values "geoserverHealthcheck" }}
{{- $secrets := 0 }} 
{{- range $name,$data := $.Values.geoserverHealthcheck.secrets | default dict }}
    {{- $secrets = add1 $secrets}}
{{- end }}
{{- range $name,$data := $.Values.geoserverHealthcheck.secrets | default dict }}
{{- if gt $secrets 1 }}
---
{{- end }}
apiVersion: v1
data:
  {{- range $key,$value := $data }}
    {{- if kindIs "string" $value }}
      {{- if contains "{{Release.Name}}" $value }}
  {{ $key }}: {{  $value | replace "{{Release.Name}}" $.Release.Name | b64enc | quote }}
      {{- else }}
  {{ $key }}: {{ $value | b64enc | quote }}
      {{- end }}
    {{- else }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
    {{- end }}
  {{- end }}
kind: Secret
metadata:
  name: {{ $.Release.Name }}-geoserver-healthcheck-secret-{{ $name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}

