{{- if hasKey (get ($.Values.geoserver | default dict) "volumes" | default dict) "secrets" }}
{{- $secrets := 0 }} 

{{- range $name,$config := $.Values.geoserver.volumes.secrets | default dict }}
{{- $secrets = add1 $secrets}}
{{- if gt $secrets 1 }}
---
{{- end }}
apiVersion: v1
data:
  {{- range $key,$value := $config.data }}
  {{ $key }}: {{ $value | toString | b64enc |  quote }}
  {{- end }}
kind: Secret
metadata:
  name: {{ $.Release.Name }}-geoserver-volume-secret-{{ $name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
