{{- if $.Values.geoserver }}

{{- $secrets := 0 }} 

{{- range $name,$data := $.Values.geoserver.secrets | default dict }}
{{- $secrets = add1 $secrets}}
{{- if gt $secrets 1 }}
---
{{- end }}
apiVersion: v1
data:
  {{- range $key,$value := $data }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
kind: Secret
metadata:
  name: {{ $.Release.Name }}-geoserver-secret-{{ $name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}

{{- end }}
