{{- if gt (len ($.Values.geoserver.customsettings | default list)) 0  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-geoserver-configmap-customsettings
  annotations:
    field.cattle.io/description: customized geoserver settings
binaryData:
  {{- range $config := $.Values.geoserver.customsettings }}
  {{$config.name}}: >- 
{{ $.Files.Get $config.path | b64enc | indent 4 }}
  {{- end }}
{{- end }}
