{{- if $.Values.geoserver }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-geoserver-configmap-scripts
  annotations:
    field.cattle.io/description: geoserver scripts
binaryData:
  geoserver_startup: >- 
{{ include "geoserver.geoserver_startup" . | b64enc | indent 4 }}
  geoserver_liveness: >- 
{{ include "geoserver.geoserver_liveness" . | b64enc | indent 4 }}
  init_geoserver: >- 
{{ include "geoserver.init_geoserver" . | b64enc | indent 4 }}
  start_geoserver: >- 
{{ include "geoserver.start_geoserver" . | b64enc | indent 4 }}
  set_geoserverrole: >- 
{{ include "geoserver.set_role" . | b64enc | indent 4 }}
  geoserver_can_restart: >- 
{{ include "geoserver.can_restart" . | b64enc | indent 4 }}
  geoserver_restart: >- 
{{ include "geoserver.restart" . | b64enc | indent 4 }}
  setup_index_page: >- 
{{ include "geoserver.setup_index_page" . | b64enc | indent 4 }}
{{- end }}
