{{- if and $.Values.geoserver (not ($.Values.geoserver.clustering | default false)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-geoserver
  namespace: {{ $.Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: default
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.statefulset-{{ $.Release.Namespace }}-{{ $.Release.Name }}-geoserver
  sessionAffinity: None
  type: ClusterIP
{{- end }}
