apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-geoserver-configmap-config-files
  annotations:
    field.cattle.io/description: customized geoserver config files
binaryData:
  admin.cluster.properties: >- 
{{ include "geoserver.admin.cluster.properties" . | b64enc | indent 4 }}
  slave.cluster.properties: >- 
{{ include "geoserver.slave.cluster.properties" . | b64enc | indent 4 }}
  index.html: >- 
{{ $.Files.Get "static/geoserverindex.html" | b64enc | indent 4 }}
  index_without_reports.html: >- 
{{ $.Files.Get "static/geoserverindex_without_reports.html" | b64enc | indent 4 }}
  livenesslogindex.html: >- 
{{ $.Files.Get "static/livenesslogindex.html" | b64enc | indent 4 }}
  {{- if hasKey $.Values "geoserverHealthcheck" }}
  default_reports.html: >- 
{{ $.Files.Get "static/default_reports.html" | b64enc | indent 4 }}
  {{- end }}
  serverinfo.html: >- 
{{ $.Files.Get "static/serverinfo.html" | b64enc | indent 4 }}
  starthistory.html: >- 
{{ $.Files.Get "static/geoserver_restarthistory.html" | b64enc | indent 4 }}
{{- if ($.Values.geoserver.clustering | default false) }}
  broker.xml: >- 
{{ include "geocluster.broker.xml" . | b64enc | indent 4 }}
{{- end }}
