{{- if and (hasKey $.Values "geoserverHealthcheck") (hasKey $.Values.geoserverHealthcheck "imagepull") }}
{{- $data := dict "auths" (dict ($.Values.geoserverHealthcheck.imagepull.domain | default "ghcr.io")  (dict "username" ($.Values.geoserverHealthcheck.imagepull.username ) "password" ($.Values.geoserverHealthcheck.imagepull.password ) )) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-geoserver-healthcheck-secret-imagepull
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson $data | b64enc }}
{{- end }}
