{{- if hasKey (get $.Values "messagequeue" | default dict) "domain" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-mq-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $.Values.messagequeue.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-mq
                port:
                  number: {{ $.Values.messagequeue.port | default 8161 }}
            path: /
            pathType: Prefix
{{- end }}
