#create a headless service for postgis
{{- if hasKey $.Values "postgis" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-postgis
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: default
      port: 42
      protocol: TCP
      targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: apps.statefulset-{{ $.Release.Namespace}}-{{ $.Release.Name }}-postgis
  sessionAffinity: None
  type: ClusterIP
{{- end }}
